Reenable all the tests

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,7 +40,6 @@ jobs:
 
   # Use a matrix of boards to run the tests
   test-matrix:
-    if: ${{ false }}  # disable for now
     needs: prepare
     runs-on: ubuntu-latest
 
@@ -144,6 +143,20 @@ jobs:
           PATCH_VERSION=$(grep "VERSION_PATCH" "Multiprotocol/Multiprotocol.h" | awk -v N=3 '{gsub(/\r/,""); print $N}')
           echo "MULTI_VERSION=($echo $MAJOR_VERSION.$MINOR_VERSION.$REVISION_VERSION.$PATCH_VERSION)" >> $GITHUB_ENV
 
+          # Get the default name prefix for binary files
+          case "$BOARD" in
+            avr|avr-*|multi4in1:avr:multiatmega328p*)
+              FWPREFIX="multi-avr"
+              ;;
+            stm32|stm32-*|t18-5in1|multi4in1:STM32F1:*)
+              FWPREFIX="multi-stm"
+              ;;
+            orx|orx-*|multi4in1:avr:multixmega32d4)
+              FWPREFIX="multi-orx"
+              ;;
+          esac
+          echo "FWFILE_PREFIX=$(echo $FWPREFIX)" >> $GITHUB_ENV
+
           cd ..
 
       - name: Configure the MULTI-Module firmware options
@@ -186,10 +199,42 @@ jobs:
           popd
 
       - name: Run Docker build
-        run: docker run --rm -t -v ${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module:/multi -e "BOARD=$BOARD" multi4in1_test:${{ github.run_id }}
+        run: |
+
+          # Delete any existing bin files
+          rm -f ${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module/Multiprotocol/*.bin
+
+          # Run the build
+          (set -x; docker run --rm -t -v ${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module:/multi -e "BOARD=$BOARD" multi4in1_test:${{ github.run_id }})
+
+          # Fail if the expected firmware file doesn't exist
+          EXPECTEDBINFILE="${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module/Multiprotocol/${FWFILE_PREFIX}-${MULTI_VERSION}.bin"
+          if [ -f $EXPECTEDBINFILE ]; then
+            ls ${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module/Multiprotocol/*.bin
+          else
+            echo -e "Expected firmware file $EXPECTEDBINFILE not found!\n"
+            ls ${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module/Multiprotocol/*.bin
+            exit 1
+          fi
 
       - name: Run Docker build with custom versioned output file name
-        run: docker run --rm -t -v ${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module:/multi -e "BOARD=$BOARD" -e "FWBINNAME=myfw-v{VERSION}.bin" multi4in1_test:${{ github.run_id }}
+        run: |
+
+          # Delete any existing bin files
+          rm -f ${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module/Multiprotocol/*.bin
+
+          # Run the build
+          (set -x; docker run --rm -t -v ${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module:/multi -e "BOARD=$BOARD" -e "FWBINNAME=myfw-v{VERSION}.bin" multi4in1_test:${{ github.run_id }})
+
+          # Fail if the expected firmware file doesn't exist
+          EXPECTEDBINFILE="${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module/Multiprotocol/myfw-v${MULTI_VERSION}.bin"
+          if [ -f $EXPECTEDBINFILE ]; then
+            ls ${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module/Multiprotocol/*.bin
+          else
+            echo -e "Expected firmware file $EXPECTEDBINFILE not found!\n"
+            ls ${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module/Multiprotocol/*.bin
+            exit 1
+          fi
 
   # Run some tests on one board
   test-other:
@@ -357,30 +402,6 @@ jobs:
 
       - name: Fail on blank board outcome 'success'
         if: steps.blank-board.outcome == 'success'
-        run: exit 1;
-
-      - name: Run Docker build with blank board name 2
-        id: blank-board2
-        if: success() || failure()
-        continue-on-error: true
-        run: |
-
-          # Delete any existing bin files
-          rm -f ${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module/Multiprotocol/*.bin
-
-          # Run the build
-          (set -x; docker run --rm -t -v ${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module:/multi -e "BOARD=stm32" multi4in1_test:${{ github.run_id }})
-
-          # Fail if a firmware file exists
-          EXPECTEDBINFILE="${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module/Multiprotocol/*.bin"
-          if ls $EXPECTEDBINFILE 1> /dev/null 2>&1; then
-            echo -e "Unexpected firmware file exists!\n"
-            ls ${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module/Multiprotocol/*.bin
-            #exit 1
-          fi
-
-      - name: Fail on blank board outcome 'success' 2
-        if: steps.blank-board2.outcome == 'success'
         run: exit 1;
 
       - name: Run Docker build with no board
